spring:
   application:
      name: screenforce-discovery-server
server:
   port: ${SERVER_PORT:5000}
eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: false
      fetch-registry: false
    server:
       enable-self-preservation: false
